name: Update Playstore metadata
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "fastlane/**"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: Update Metadata
        run: bundle exec fastlane android update_playstore
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
