name: Verify pull requests
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run all the tests
        run: ./gradlew test
      - name: Stop Gradle
        run: ./gradlew --stop

  check_conventional_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
